#!/bin/bash
## This will will check record content and update cloudflare if necessary
## Script will take the following parameters
## -e : Cloudflare login email
## -k : Cloudflare login key
## -z : Cloudflare zone name
## -n : Cloudflare FQDN
## -i : interface to be used (optional on type A/AAAA)
## -c : content to be updated (required except for A/AAAA records)
## -t : DNS record Type
## -o : ipv4 hostname PPPoE


# Set Default for Variables 
source ./config.txt

while getopts ":e:k:z:n:i:t:c:o:" opts
do
   case "$opts" in
      "e")
         auth_email="$OPTARG"
         ;;
      "k")
         auth_key=$OPTARG
         ;;
      "z")
         zone_name="$OPTARG"
         ;;
      "n")
         record_name="$OPTARG"
         ;;
      "t")
         rec_type=$OPTARG
         ;;
      "i")
         iface=$OPTARG
         ;;
      "c")
         content="$OPTARG"
         ;;
      "o")
         ipv4outsidename="$OPTARG"
         ;;
      "?")
         echo "Unknown option $OPTARG"
         exit 1
         ;;
      ":")
         echo "Missing argument for option $OPTARG"
         exit 1
         ;;
      esac
done
if [ "$content" == "" ]; then
   if [ "$rec_type" == "AAAA" ]; then
      content=`/bin/ip -6 addr show $iface|sed -n 's%.*inet6\s\(.*\)/64.*global.*%\1%p'`
   elif [ "$rec_type" == "A" ]; then
      #content=`/bin/ip -4 addr show $iface|sed -n 's/.*inet\s\(.*\)\/24.*/\1/p'`
      content=`host -4 $ipv4outsidename | sed -e 's/^.* has address *//'`
   elif [ "$content" == "" ]; then
      echo "Must specify content on record type other than A/AAAA!"
      exit 1
   fi
fi

echo $(date)
echo "Checking $rec_type for $record_name"
zone_id=`curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$zone_name" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json" | \
sed -n 's/.*result":\[{"id":"\([[:alnum:]]*\)".*/\1/p'`

echo "Zone ID : $zone_id"

record_str=`curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records?type=$rec_type&name=$record_name" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json"`

record_id=`echo $record_str|sed -n 's/.*result":\[{"id":"\([[:alnum:]]*\)".*/\1/p'`
echo "Record ID: $record_id"

current_content=`echo $record_str| sed -n 's/.*content":"\(.*[^"]\)","proxiable.*/\1/p'`
echo "Current Content : $current_content"


if [[ $current_content == $content ]]; then
    echo "Content not changed.  Exiting."
    exit 0
else
    echo "Content Changed.  Update Cloudflare."
    echo "Zone ID: $zone_id"
    echo "Record ID: $record_id"
    echo "Current Content: $current_content"
    echo "New Content: $content"
fi

update=`curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records/$record_id" \
-H "X-Auth-Email: $auth_email" \
-H "X-Auth-Key: $auth_key" \
-H "content-Type: application/json" \
-d "{\"id\":\"$zone_id\",\"type\":\"$rec_type\",\"name\":\"$record_name\",\"content\":\"$content\"}"`

if [[ $update == *"\"success\":false"* ]]; then
    message = "API UPDATE FAILED.  DUMPING RESULTS:\n$update"
    echo "$message"
    exit 1
else
    message="$rec_type changed to: $content"
    echo "$message"
fi
